# Generated by Django 6.0.2 on 2026-02-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0002_alter_post_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='about',
            field=models.TextField(max_length=2200),
        ),
    ]
