# Generated by Django 6.0.2 on 2026-02-21 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0005_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Like', 'verbose_name_plural': 'Likes'},
        ),
    ]
