# Generated by Django 6.0.2 on 2026-02-23 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0007_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(13, message='Тобі має бути хоча б 13 років!'), django.core.validators.MaxValueValidator(100, message='Ну ти і довгожитель. Введи реальний вік!')]),
        ),
    ]
